## CLASS TASK 2

### 
a. 
Matrix A = 2 x 3 matrix

    Matrix B = 3 x 2 matrix






In [ ]:
### 
b.
Yeah, the matrixes can be multiplied because matrix A has 3 - columns and matrix B has 3 - rows. 
Since both matrixes has the same number of columns and rows, it can be multiplied.
Also, on the other way, both matrix has 2 - rows and 2 - columns. It can be multiplied.



In [1]:
import numpy as np
matrix_A = np.array([[2, -1, 3], [0, 4, 1]])
matrix_A

array([[ 2, -1,  3],
       [ 0,  4,  1]])

In [5]:
matrix_B = np.array([[1, 2], [-2, 0], [5, -3]])
matrix_B

array([[ 1,  2],
       [-2,  0],
       [ 5, -3]])

In [6]:
Multiply = matrix_A @ matrix_B
Multiply

array([[19, -5],
       [-3, -3]])

### Inverse both Matrix

In [7]:
Multiply_inverse = matrix_B @ matrix_A
Multiply_inverse

array([[  2,   7,   5],
       [ -4,   2,  -6],
       [ 10, -17,  12]])